config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
# class TasksController < ApplicationController
#   before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = Task.all
  end

#   def show
#   end
  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

#   def create
#     task = Task.new(task_params)
#     task.save
#     redirect_to tasks_path
#   end

  def edit
    @task = Task.find(params[:id])
  end
#   def edit
#   end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end
#   def update
#     @task.update(task_params)
#     redirect_to task_path(@task)
#   end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
#   def destroy
#     @task.destroy
#     redirect_to tasks_path
#   end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

#   private

#   def set_task
#     @task = Task.find(params[:id])
#   end

#   def task_params
#     params.require(:task).permit(:title, :details, :completed)
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit an existing task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to tasks", tasks_path %>

app/views/tasks/index.html.erb
<!-- loop and display -->
<h1>My Tasks</h1>

<% @tasks.each do |t| %>
  <!-- input tag -->
  <!-- type checkbox and task id -->
  <%= link_to t.title, task_path(t) %>
  <%= link_to "Edit", edit_task_path(t) %>
  <%= link_to "Delete", task_path(t), method: 'DELETE' %><br>
<% end %>

<%= link_to "Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= form_for(@task) do |f| %>
  <h5><%= f.label :title %></h5>
  <%= f.text_field :title %>
  <h5><%= f.label :details %></h5>
  <%= f.text_field :details %><br>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<h2><%= @task.details %></h2>
<%= link_to "Back to list", tasks_path %>